#best_config_

Graphical_interface: false
ShowTrajectory: false
Trajectory_length: 50
TimeBetweenFrames: 0.1
LoadModel: false
Path2Model: "../TLDmodel"
SavingFile: "../TLDmodel"
Tracking3D: false
queue_size : 100
